name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        lua: [lua, luajit]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      run: make ${{matrix.lua}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./${{matrix.lua}} -e "print(_VERSION)"

  Android:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK_VER: 28.2.13676358
      ANDROID_NDK: /usr/local/lib/android/sdk/ndk/28.2.13676358
    strategy:
      matrix:
        lua: [Lua, LuaJIT]
        target: [Android64, Android]

    steps:
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Install NDK
      run: sdkmanager "ndk;$ANDROID_NDK_VER"
    - name: install libc6-dev-i386
      if: ${{ matrix.target == 'Android' && matrix.lua == 'LuaJIT' }}
      run: sudo apt update && sudo apt-get install libc6-dev-i386 --fix-missing
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: make ${{matrix.target}} LUA_ENGINE=${{matrix.lua}}

  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        lua: [Lua, LuaJIT]

    steps:
    - uses: lukka/get-cmake@latest
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Config
      run: cmake -H. -Bbuild -DLUA_ENGINE=${{matrix.lua}}
      shell: cmd
    - name: Build
      run: cmake --build build --config Release
      shell: cmd
    - name: Test
      working-directory: ${{github.workspace}}/build/${{env.BUILD_TYPE}}
      run: ${{ matrix.lua }}.exe -e "print(_VERSION)"
      shell: cmd

  iOS:
    runs-on: macos-latest
    strategy:
      matrix:
        lua: [Lua, LuaJIT]
        platform: [OS64]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      run: make iOS LUA_ENGINE=${{ matrix.lua }} PLATFORM=${{ matrix.platform }}

