name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        lua: [lua]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: make ${{matrix.lua}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./${{matrix.lua}} -e "print(_VERSION)"


