name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        lua: [lua, luajit]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: make ${{matrix.lua}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./${{matrix.lua}} -e "print(_VERSION)"

  iOS64_LuaJIT:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: depends
      run: brew install mingw-w64
    - name: Build
      run: make iOS PLATFORM=OS64

  iOS_Lua:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: make iOSWithLua

  Android64:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK: /usr/local/lib/android/sdk/ndk-bundle

    steps:
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: make Android64

