name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        lua: [lua, luajit]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: make ${{matrix.lua}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./${{matrix.lua}} -e "print(_VERSION)"

  iOS64_LuaJIT:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: depends
      run: brew install mingw-w64
    - name: Build
      run: make iOS PLATFORM=OS64

  iOS_Lua:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: make iOSWithLua

  Android64:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK: /usr/local/lib/android/sdk/ndk/23.1.7779620

    steps:
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Install NDK
      run: sdkmanager "ndk;23.1.7779620"
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: make Android64

  Windows:
    runs-on: windows-latest

    steps:
    - uses: lukka/get-cmake@latest
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Config
      run: cmake -H. -Bbuild -DLUAJIT_BUILD_ALAMG=ON
      shell: cmd
    - name: Build
      run: cmake --build build --config Release
      shell: cmd
    - name: Test
      working-directory: ${{github.workspace}}/build/${{env.BUILD_TYPE}}
      run: luajit.exe -e "print(_VERSION)"
      shell: cmd

